export * from './editorconfig';
export * from './eslintignore';
export * from './eslintrc';
export * from './gitignore';
export * from './jestconfig';
export * from './license';
export * from './prettier';
export * from './tsconfig';
export * from './indexTest';
